### PR TITLE
Feature: Static asset updates

### LINKED ISSUE #219: Add 'dist' folder for easily consumable assets

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #219. 
Updates to prepare certain components for being ready to generate static assets.

### CODE REVIEW

**Comment by bspeare** [comment]
The new prototype bar looks good.  One thing that is missing is a negative margin on the block iowa at the `@container` breakpoint so that the "I" aligns up with the site name and the edge of the container. 

Screen Shot 2020-06-03 at 10 42 11 AM

And also padding for the Site Name once it its the container edge:

Screen Shot 2020-06-03 at 10 44 10 AM



Screen Shot 2020-06-03 at 10 42 11 AM

**Comment by bspeare** [comment]
Alignment of smaller and larger size font sizes for Site Name align a bit differently at the mobile breakpoint. 

Screen Shot 2020-06-08 at 11 01 40 AM
Screen Shot 2020-06-08 at 11 01 31 AM

Both appear a bit to the left of the logo tab.  The logo tab is using `padding: 25px` and the Site name is using `$gutter`.

**Comment by bspeare** [comment]
Screen Shot 2020-06-08 at 11 16 11 AM

- Maybe we should add more margin space for social media icons for mobile?
- And change socket links to stack on mobile?

**Comment by pyrello** [comment]
Currently, at the largest size, the tab logo is incorporating the padding from desktop version the full height IOWA bar, so that their is more padding on the top:
Screen Shot 2020-06-08 at 11 23 01 AM

Since that is really a thing that is pertinent to the IOWA bar, it seems like for the logo itself, it should just have even padding, then be altered to have that spacing in the context of that version of the IOWA bar.

@bspeare What do you think?

**Pull request merged**
