### PR TITLE
Event Card Variant

### PR DESCRIPTION
**Pull request by GaryRidgway**
This PR is to create a variant for the card component that translate everything that the event component could do in to it.

### CODE REVIEW

**Comment by bspeare** [comment]
Should we update the class names in the card details?  The author class seems like it should change to `subtitle` or something related. 

- `card__date`
- `card__author`
- `card__label`

**Comment by pyrello** [comment]
I was wondering about this too. Specifically, for the date, I was wondering about whether we might ever want to include other types of icons in a similar fashion for other arbitrary pieces of data that get included in the card. Since we use it for everything :)

**Comment by GaryRidgway** [comment]
author has been replaced! We are subtitle now!

**Review by pyrello — APPROVED** [review]
Tested via integration in uiowa/uiowa project.

**Pull request merged**
