### PR TITLE
Horizontal Nav Variants

### PR DESCRIPTION
**Pull request by GaryRidgway**
# To Test
1. Pull down this branch 
2. Change the `hidden: true` value on the second line of `src/components/menus/main-menu/main-menu.config.yml` to `hidden: false` (Do not commit this)
3. Spin up your local site with `npm run watch`
2. Under Menus > Main Menu check that all horizontal styles have:
    1. Proper `a11y` contrast for text
    2. A white active tab, unless it is `bg--white` or `bg--white--pattern--brain`, In which case they should have a Grey active tab.
    3. Yellow arrowed border at the bottom and yellow link separators, unless it is `bg--gold` or `bg--gold--pattern--brain`, in which case they should have a Grey arrowed border at the bottom and Grey link separators.

### CODE REVIEW

**Comment by bspeare** [comment]
Stil to do:

- [ ] Update `main-menu.scss` to use the new styles attached to `main--secondary--vertical` class: https://github.com/uiowa/uids/blob/main/src/components/menus/main-menu/main-menu.scss#L95
- [ ] Verify that if no `bg-` wrapper class exists, the active state will have a gray background instead of white. 
- [ ] Verify `a11y` contrast if other background colors are used, you might need to attach the `background.css` component to this if it is not already attached.

**Comment by joewhitsitt** [comment]
pulling down to test

**Comment by joewhitsitt** [comment]
> A white active tab with a yellow arrowed border at the bottom, uless it is bg--white or bg--white--pattern--brain, In which caste they should have a Grey active tab.

The gold/gold brain have a grey border. If that is working by designed and just a mistake on the testing criteria then I approve.

Can't find the original issue to see what other test criteria there might be.

Also, I had to change it to `hidden: false` to review it. Not sure what the plan is there.

**Comment by GaryRidgway** [comment]
Ah, you are correct @joewhitsitt , it was meant to say the gold variants, thanks for the catch.

**Comment by GaryRidgway** [comment]
I went back through and added Grey link separators for the gold backgrounds as they were not showing up because the colors were identical. I've also added some clarity to testing criteria, hopefully this makes it more clear.

**Review by joewhitsitt — APPROVED** [review]
Thanks for clearing up the test instructions. Looks as described.

**Pull request merged**
