### PR TITLE
Storybook 8 migration

### PR DESCRIPTION
**Pull request by bspeare**
# How to test

- `yarn install` 
- `yarn storybook`
- Compare against http://uids.brand.uiowa.edu/latest
- Click through each component story, test controls, verify that HTML is still available. 
- Review code changes and try to identify anything that could still be removed or anything that has been removed that we still might need. 

## Test build process:

-    `yarn production`
-    `npx http-server ./www`
-     Go to the Introduction page and confirm that CSS files are listed using the version number from package.json.
-     Go to the Brand Bar docs page and confirm that the CSS files are listed using the version number from package.json.

Deprecated Items changed:
- @storybook/preset-scss has been [deprecated](https://github.com/storybookjs/presets/tree/master/packages/preset-scss).  Moved to `storybook-addon-sass-postcss` but it looks like there are other options too. 
- Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.  More info: https://sass-lang.com/d/legacy-js-api
- Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`. More info: https://sass-lang.com/d/mixed-decls
- Deprecation Warning: lighten() is deprecated. More info: https://sass-lang.com/d/color-functions
  - Switched to `@use "sass:color";`

Deprecated Items todo in another issue:
- sass import rules are deprecated and will be removed in Dart Sass 3.0.0. More info and automated migrator: https://sass-lang.com/d/import

### CODE REVIEW

**Comment by pyrello** [comment]
Looks like the build is failing on this...

**Comment by GaryRidgway** [comment]
pulling to review

**Comment by joewhitsitt** [comment]
Alan gave me the go ahead to take over review for the moment.

**Comment by joewhitsitt** [comment]
Version 8
Screenshot 2024-10-30 at 10 19 40 AM

Latest
Screenshot 2024-10-30 at 10 19 48 AM

Do you recall what, if anything we can do with this? It toggles now without showing anything.

**Comment by joewhitsitt** [comment]
Also, I am not sure I follow what this means:

>are listed using the version number from package.json

**Comment by bspeare** [comment]
@joewhitsitt if you hover over the links here on http://localhost:6006/?path=/docs/introduction--docs, it will use the uids version number in the link. 

Screenshot 2024-10-30 at 10 42 48 AM

**Comment by joewhitsitt** [comment]
okay. yes. it does for both.

**Comment by joewhitsitt** [comment]
> Version 8 Screenshot 2024-10-30 at 10 19 40 AM
> 
> Latest Screenshot 2024-10-30 at 10 19 48 AM
> 
> Do you recall what, if anything we can do with this? It toggles now without showing anything.

Looks like we can replace

```
source: {
        code: null,
      },
```
with

```
canvas: {
        sourceState: "none"
      },
```

https://github.com/storybookjs/storybook/issues/14686#issuecomment-2414061283

**Comment by joewhitsitt** [comment]
Looking good to me. ✅ 

Do we do formal approval for these? Do we move straight on to reviewing https://github.com/uiowa/uiowa/pull/8144?

**Comment by bspeare** [comment]
Thanks @joewhitsitt, you can approve if you'd like.   I will probably bring https://github.com/uiowa/uiowa/pull/8144 up for review for the next sprint.

**Review by joewhitsitt — DISMISSED** [review]

**Comment by joewhitsitt** [comment]
Talked with @bspeare about merging this as-is to help make work on https://github.com/uiowa/uiowa/issues/6695 easier since there are node 14 version issues with `4.x`

**Review by joewhitsitt — APPROVED** [review]

**Pull request merged**
