### PR TITLE
Banner Video Variant

### PR DESCRIPTION
**Pull request by GaryRidgway**
This PR is tracking all commits that are for adding the video  variant to the banner component similar as to how it is on the hero component.

## To Test

- [x] Test that the `Button Row` variant has buttons that individually work and do not link to the same thing as clicking the whole banner. Also ensure that the link in the text functions independently as well.
- [x] Test that the Banner can be unlinked while there are multiple buttons
- [x] Test that both the `Large, content centered ` variant and the `Button Row` variant have buttons that can be right clicked to open them in a new tab
- [x] Test that the Banner video works
- [x] Test that a banner video with a button row works
- [x] Test that the auto-play/auto-pause for banner video works
- [x] Test that the video is available and reasonably shown at all banner sizes
- [x] Test that there can be multiple videos and that you can play and pause them independently.

### CODE REVIEW

**Comment by GaryRidgway** [comment]
This is specifically for issue #394

**Comment by GaryRidgway** [comment]
The scope of this PR has now expanded to include #393.

**Comment by bspeare** [comment]
Just checked https://uids.brand.uiowa.edu/branches/i394-banner-video/components/preview/banner--video.html on IE and I can confirm that it does not work.   Do we want this video loop to work with IE11?

**Comment by bspeare** [comment]
I'm working on adding an IE style fix so that the banner will display as a normal image banner.   I think getting the video play/pause buttons to work in IE might be work for a featured sprint.

**Comment by richardbporter** [comment]
> buttons that individually work and do not link to the same thing as clicking the whole banner.

Is that something we need to allow/support/implement? I don't think we can do that in Drupal. If one link is provided, the whole banner is linked. Otherwise, the banner is not linked.

**Comment by GaryRidgway** [comment]
That should be accounted for in the JS, that is why i was accounting for two separate link fields. Perhaps we should have a 'banner link' field and then a multi-value 'button links' field? My initial implementation was trying to allow for as little change of old framework as possible.

**Comment by richardbporter** [comment]
I did not get that impression from https://github.com/uiowa/uiowa/issues/2404. A separate field of one link and another of up to two links seems less than ideal for the editor. 

I thought linking the whole banner was an a11y workaround for two identical links?

**Comment by pyrello** [comment]
On the Drupal side, this should consist of changing the limit on the current link field to allow for 3 links instead of 1. The idea is that the banner will function as fully clickable if, and only if, there is one button link. If there are multiple button links, then we cannot determine which link clicking the banner should direct you to. In that case, I think that the behavior of having the entire banner linked would be confusing to the end user.

**Comment by joewhitsitt** [comment]
pulling down to see if I can help with the consolidation task discussed in slack

**Comment by joewhitsitt** [comment]
uh, getting errors locally with npm run watch

**Comment by joewhitsitt** [comment]
deleting node_modules is causing more errors. i might not be the knight in shining armor for this one.

**Comment by joewhitsitt** [comment]
i still haven't been able to get a build to finish here. i might try to delete the repo locally and start fresh

**Comment by joewhitsitt** [comment]
So, i'd like some eyes on my commits here. Alan said we could basically copy/paste banner.twig to banner-multiple if it is the correct approach and that he was going to get the js link working again based on the updated structure.

Is this the right approach?

**Comment by pyrello** [comment]
I'm pulling this down to review the changes.

**Comment by pyrello** [comment]
I have not done anything to resolve how we are going to move forward with the accessibility strategy that was adapted from cards, which was, in turn, adapted from this article: https://inclusive-components.design/cards/

I did, however, make two updates to simplify maintainability:
* Added a video template that can be included in the banner, rather than burdening the banner with that.
* Refactored the `banner--multiple.twig` template to use the existing single banner template.

**Comment by GaryRidgway** [comment]
I've re-tested all of the new changes and they all seem to work great except for single buttons being able to be right clicked because of an accessibility quirk. upon discussion with both Sean and Ben This seems to be a minimally detrimental problem and not a real hinderance to the spirit of this pull request.

**Comment by pyrello** [comment]
Great work on this @GaryRidgway and everyone else who pitched in.

**Comment by bspeare** [comment]
Pulling this down to test.

**Comment by bspeare** [comment]
Looks like we have one more issue to fix, a conflict between the `hero.js` and `banner.js`:

Screen Shot 2020-12-04 at 1 18 46 PM

**Comment by pyrello** [comment]
@bspeare Can we just stop using hero.js?

**Comment by bspeare** [comment]
@pyrello I think we would need to socialize that a bit more to stakeholders beforehand.  We can only load the `banner.js` if a video is uploaded in https://github.com/uiowa/uiowa/pull/2545?

**Comment by bspeare** [comment]
The entire banner doesn't seem clickable when I have one link in place on https://github.com/uiowa/uiowa/pull/2609.  It works on https://localhost:3000/components/preview/banner--default, but not on the uiowa pr.  Do we need to update the banner template there?

**Comment by pyrello** [comment]
@bspeare I changed the query selector for the title in banner.js to target a generic `.headline` class instead of the `bold-headline`. This was already present on the headline template here (which is why it worked), but hadn't been added to the template in UIDS Base yet.

**Comment by bspeare** [comment]
@pyrello It looks like that did fix the issue.  I'll need to do some further testing with how the `.headline` class will have an impact with regards to how this is set: https://github.com/uiowa/uids/blob/main/src/components/headline/headline.scss#L58-L68.

**Review by bspeare — APPROVED** [review]
I've tested this locally and in the two pull requests in `uiowa`.  Nice work!

**Pull request merged**
