### PR TITLE
4.x button updates

### LINKED ISSUE #706: 4.x - Button component updates
# Motivation
The [Brand Icon Browser](https://github.com/uiowa/brand-icon-browser) needs an exportable button component that has the following features, most of which are available in [the current button component](https://uids.brand.uiowa.edu/components/detail/button--row.html):

- Background color options
- The ability to have an appropriately styled Font Awesome Icon
- A possible "block" size option that takes the full width of the container, like the following example:
Screen Shot 2022-06-09 at 1 54 27 PM

# Proposed solution
- [x] Incorporate a transparent background option. The transparent option needs to have an outline, otherwise the text and icon will just be floating in space.  
  - Use https://github.com/uiowa/uids/pull/711 as a starting point for base CSS. 
    -  https://github.com/uiowa/uids/blob/acc28e4f0aae5ad5b92adb3d4871d941baf808e4/src/assets/scss/_utilities.scss
    - https://github.com/uiowa/uids/blob/acc28e4f0aae5ad5b92adb3d4871d941baf808e4/src/components/button/button.scss
- [x] Add an `icon` prop that allows for the display of an arbitrary FA icon. This will likely replace the `arrow` prop.
- [x] Add a `block` prop to set display of button to be full-width.
- [x] Abstract the outline prop and related logic from the Card component into a mixin which can be shared with the button.
- [x] Change borderless class to not be element specific

```
Props:

Color:
- Primary (gold)
- Secondary (black)
- Tertiary (white)
- Transparent (with border/outline added by default)
- Link (border removed no matter what)

Borderless:
- False/True
```

### PR DESCRIPTION
**Pull request by GaryRidgway**
Resolves #706
Resolves https://github.com/uiowa/uids/issues/710

## To test
- check to see that the transparent option is present, and that the transparent borderless option has link underlining.
- test that going to font awesome and copying an icon ([An example icon is here, copy everything in the `<i>` tag](https://fontawesome.com/v5/icons/dog?s=solid))
- Test that the full width option is available and working properly
- check that the borderless option works for both the card and button
- Test background color combinations, if possible https://github.com/uiowa/uids/pull/716#issuecomment-1170507596

### CODE REVIEW

**Comment by pyrello** [comment]
@GaryRidgway It seems like the last thing you need to do here is write up testing instructions.

**Comment by quamsta** [comment]
I'll likely do a test run on adding this to the Brand Icon Browser today, not sure if that counts as a full review, but I'll put anything of note in here.

**Comment by quamsta** [comment]
@pyrello , @GaryRidgway  does the building/compiling of the `uids` module's  `dist/` folder happen during a GitHub action? I attempted to import the components in the Brand Icon Browser, but I quickly realized that the statement I was using:

`import { UidsBrandBar, UidsButton } from "uids";`

...was still importing the old version of the `UidsButton` component. Does the `dist/` folder need to be built in the `4.x-button-updates` branch or will it happen automatically when it's merged into `4.x`?

**Comment by pyrello** [comment]
@quamsta This process is not automated yet :|

Here is the relevant issue: https://github.com/uiowa/uids/issues/100. Running `yarn build` should take care of it. Sorry we forgot to do this the other day.

**Comment by quamsta** [comment]
@pyrello  All good! I attempted to run `yarn install` and `yarn build` within Icon Browser's `node_modules/uids` folder, which did succeed, but upon trying to use the components, I received this error:

```
app.js:1201 Uncaught TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.esm-bundler.js?9feb:2947:1)
    at Proxy._sfc_render (uids.es.js?175d:1:1)
    at renderComponentRoot (runtime-core.esm-bundler.js?d2dd:895:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js?d2dd:5059:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js?89dc:185:1)
    at setupRenderEffect (runtime-core.esm-bundler.js?d2dd:5185:1)
    at mountComponent (runtime-core.esm-bundler.js?d2dd:4968:1)
    at processComponent (runtime-core.esm-bundler.js?d2dd:4926:1)
    at patch (runtime-core.esm-bundler.js?d2dd:4518:1)
    at mountChildren (runtime-core.esm-bundler.js?d2dd:4714:1)
```

Which I Googled around for and found this post from: https://github.com/vuejs/core/issues/4344

> That's because you have two distinct copies of the Vue package being used, one in each package.
> 
> Vue uses a global singleton to track the current rendering instance - having more than one copy included will inevitably lead to such issues.

So I assumed I somehow duplicated or otherwise blew up my local UIDS components/package by attempting to run `yarn build` inside of `node_modules`, but I'm not sure.

**Comment by quamsta** [comment]
Yeah ignore that above comment-- there was something wrong locally with my environment.

**Comment by bspeare** [comment]
# Changes that need to be documented

- The major change in this that we need capture in our changelog is that buttons using `bttn bttn--outline bttn--tertiary` like on https://tippie.uiowa.edu/kira-price-story-undergraduate will render with a white background instead of being transparent.   The button classes would need to be changed to `bttn bttn--transparent` like on https://tippie.uiowa.edu/iowa-mba/curriculum/dual-degrees where the sections alternate between background colors. 
- Additionally, we will need to change the default card button classes to `bttn bttn--transparent bttn--sans-serif`. 
- `bttn__apply` has been removed.
- `bttn__link` has been removed `bttn borderless bttn--transparent bttn--sans-serif` should be used as a replacement.

**Comment by bspeare** [comment]
Can we figure out a way to test these buttons with multiple background classes in this pr?  I've been working with https://uids.brand.uiowa.edu/branches/feature_button_tertiary_fixes/components/preview/kitchen-sink.html to test, but it is not ideal.

**Comment by bspeare** [comment]
Should we add https://github.com/uiowa/uids/issues/714 to `_border.scss` here?

**Comment by bspeare** [comment]
Did we also want to remove the BEM nesting on https://github.com/uiowa/uids/blob/2a8460641aaf054fb23cdbe04e1d231de74f422c/src/components/button/button.scss?

**Comment by pyrello** [comment]
> `bttn--apply` has been removed. It is only used in viewbooks and perhaps we should move it to https://github.com/uiowa/vuejs-site-template?

What is `bttn--apply` doing?

**Comment by bspeare** [comment]
I thought it was used in the viewbooks but I guess not.   I would guess I added it for a `uiowa.edu` header button that is no longer in use.

**Comment by GaryRidgway** [comment]
Screen Shot 2022-06-30 at 10 08 47 AM
it is used on viewbooks to add the proper icon to an apply button
this is live on the admissions viewbook

**Comment by GaryRidgway** [comment]
it serves the same functionality as `bttn--visit`, `bttn--ask`, and `bttn--connect`

**Comment by bspeare** [comment]
@GaryRidgway I updated the class name in https://github.com/uiowa/uids/pull/716#issuecomment-1170505678.  It is a different class than the viewbook example.

**Comment by bspeare** [comment]
I removed the BEM nesting and also removed the `bttn--link` modifier and added a entry for it in https://github.com/uiowa/uids/pull/716#issuecomment-1170505678.

**Comment by GaryRidgway** [comment]
Future work:

- remove medium option
- add the option to align the icon left.
- remove serif option

**Comment by bspeare** [comment]
Should we remove this `serif` option?

Screen Shot 2022-06-30 at 1 11 17 PM

**Review by quamsta — DISMISSED** [review]
Hey all, these buttons are looking pretty fresh. I was able to use the latest commit from this branch in the Icon Browser and tested several variations and they're all looking pretty nice, landed on tertiary, small:

Screen Shot 2022-07-05 at 11 03 50 AM

Screen Shot 2022-07-05 at 11 04 01 AM

I'm going to approve this since it looks great on my end, but anyone should feel free to add their own review/approval here before this gets merged. Thanks everyone!

**Comment by pyrello** [comment]
> Should we remove this `serif` option?

I thought we specifically decided to add that. Do you want to not have it anymore?

**Comment by bspeare** [comment]
@pyrello I don't see us using the serif font any time soon.   Maybe we could shelve it for now?

**Review by quamsta — APPROVED** [review]
Approving this because apparently my old review got stale!

**Pull request merged**
