### PR TITLE
3.x - patterns and css variables updates for off-brand theme

### PR DESCRIPTION
**Pull request by GaryRidgway**
This pr switches our primary and secondary color variables to using css variables.  The background patterns have also been adjusted to work with these new variables.

### CODE REVIEW

**Comment by bspeare** [comment]
Let's try to adjust the gold svgs using https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images.  

```
.bg--white--pattern--brain {
  -webkit-filter: hue-rotate(220deg) saturate(5);
  filter: hue-rotate(220deg) saturate(5);
}
```

**Comment by bspeare** [comment]
We will also need to convert all the particle pattern pngs https://uids.brand.uiowa.edu/assets/images/particle-pattern--gold.png to a svg so we can switch the color.

**Comment by bspeare** [comment]
Also, test nested background colors on the kitchen sink page to make sure the color contrast ratio remains readable.

**Comment by pyrello** [comment]
Why is this PR necessary?

**Comment by bspeare** [comment]
We are still using these files in uids_base @pyrello .

**Review by pyrello — APPROVED** [review]
Reviewed, not tested.

**Pull request merged**
