### PR TITLE
Adjust card and banner click handling JS

### PR DESCRIPTION
**Pull request by pyrello**
Related to #553, but does not resolve

### CODE REVIEW

**Comment by pyrello** [comment]
I have adjusted this to include banners by moving the logic into a shared assets JS file and adjusting the implementation to use component-agnostic classes. Also just letting `<a>` and `<button>` clicks do what they would have originally have done and only applying the click behavior otherwise.

**Comment by richardbporter** [comment]
Adjusted PR description to not resolve the original issue.

**Review by joewhitsitt — APPROVED** [review]
Approving knowing that this is a step forward but does not address https://github.com/uiowa/uids/issues/553

**Comment by pyrello** [comment]
I've closed #553 as "won't fix" based on my previous investigation.

**Pull request merged**
