### PR TITLE
Add uiowa_program_block template and styling to uids.

### PR DESCRIPTION
**Pull request by mark-bennett-uiowa**
Added initial template and styling for uiowa_program_block. Will add TODO shortly.

### CODE REVIEW

**Comment by pyrello** [comment]
Preview URL: https://uids.brand.uiowa.edu/branches/feature_uids_program_block/components/detail/program.html

**Comment by bspeare** [comment]
I added a variant that uses the underlined heading style.  The preview urls can now be viewed under "Programs" once the pages are built at:

https://uids.brand.uiowa.edu/branches/feature_uids_program_block/index.html

**Comment by bspeare** [comment]
@mark-bennett-uiowa Is there any real program content we can use for this component?

**Comment by mark-bennett-uiowa** [comment]
@bspeare you could use something from [https://americanstudies.prod.drupal.uiowa.edu/undergraduate](https://americanstudies.prod.drupal.uiowa.edu/undergraduate).

**Comment by mark-bennett-uiowa** [comment]
@bspeare Any chance you could take a quick peak at the latest updates I pushed on this? If so, Id love to get this merged in. It might be close to usable.

**Comment by pyrello** [comment]
@mark-bennett-uiowa Just to clarify, are you wanting this to become a part of UIDS in that it would show up as part of the style guide? I'm still not totally clear where this would sit inside the broader project. If you want to start using the CSS generated as part of this as a partial inside of UIDS Base in the meantime, I think that would be a good starting point. I'd like to have a bit more clarity on what the intention is with this or items similar to it before we merge it in.

**Comment by pyrello** [comment]
@bspeare and @mark-bennett-uiowa I think that we should close this PR in favor of adding this to UIDS base. We are starting work on the 4.x branch and not going to introduce any new features in the 3.x branch. The work done in this PR won't be compatible with the 4.x branch. Finally, I'm not sure that this block is something that should be defined in UIDS since it seems like it is largely a compilation of existing components with a little bit of glue. It seems more appropriate that it should find a home in a custom module that adds the block content type in the `uiowa` repo.

If you disagree with my thinking here, please reopen.

**Pull request closed without merging**
