### PR TITLE
Add brand bar and logo components, clean-up

### LINKED ISSUE #691: Add exportable IOWA bar component
# Motivation

We have identified this as the first and most easy deliverable to start to allow https://github.com/uiowa/brand-icon-browser to be able to consume components from UIDS.

# Proposed solution

Build a `iowa-bar` component in the 4.x branch

### LINKED ISSUE #692: Decision - How do we set up consuming UIDS components?
# Motivation

We have to decide on how components will be consumed from applications that are using it as a dependency. 

This is something we need to figure out related to UIDS components being consumed in https://github.com/uiowa/brand-icon-browser.

Here are some potential options:
1. Entire library packaged as a single entry point: Import: `import Uids from 'uids'`; Usage: `Uids.Button`
2. Each component packaged as part of a main library that can be imported in its entirety: Import: `import { UidsButton } from 'uids'`
3. Each component package separately: `import UidsButton from 'uids-button'`

### PR DESCRIPTION
**Pull request by pyrello**
Resolves #691 
Resolves #692 

# To test
- Review[ code changes](https://github.com/uiowa/uids/pull/694/files)
- Review https://uids.brand.uiowa.edu/branches/iowa_bar/ to see Brand Bar and Logo components. Make note of things that seem off.
- Note that test passed below :)

### CODE REVIEW

**Comment by bspeare** [comment]
Are the default slots supposed to be styled?
Screen Shot 2022-05-24 at 4 01 48 PM

**Comment by pyrello** [comment]
I’m trying out changing the conditions under which GH actions builds the docs. Going forward (for PRs based on the 4.x branch) the workflow to build the docs should only run if the PR is ready for review. This means that you can push to your hearts content without incurring that overhead, but if you want to actually build the docs, you need to mark the PR as ready for review, at least temporarily. Marking it as ready for review should immediately trigger that task.

**Comment by pyrello** [comment]
> Are the default slots supposed to be styled?

Related: https://github.com/uiowa/uids/issues/695

**Comment by GaryRidgway** [comment]
I will be taking a look at this soon!

**Comment by GaryRidgway** [comment]
Based on test instructions and that there were no glaring issues, I think this is good!

**Review by GaryRidgway — APPROVED** [review]
Approved!

**Pull request merged**
