### PR TITLE
update with finalized wordmark 

### PR DESCRIPTION
**Pull request by joewhitsitt**
relates to https://github.com/uiowa/uiowa/issues/1322

### CODE REVIEW

**Comment by bspeare** [comment]
@joewhitsitt I'm noticing some spacing issues in this update within the tab that might take some further time to fix.

**Comment by joewhitsitt** [comment]
good eye. i can try to revisit the vertical change (not width changes based on kerning) if you want. might be easier in CSS though

**Comment by bspeare** [comment]
Yeah, the vertical change is the most challenging if there's anything you can do there without CSS.

**Comment by joewhitsitt** [comment]
I think i got the png almost exactly. The svgs are another story...

**Comment by joewhitsitt** [comment]
Going to try again with the updated file organization

**Pull request closed without merging**
