### PR TITLE
Feature: A few misc follow-ups to links on gray background colors

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uiowa/issues/4455

# How to test

- Go to the kitchen sink and verify that the `<figcaption>` is readable on all background colors and links within are blue on white and gray backgrounds. https://uids.brand.uiowa.edu/branches/feature_figcaption_fix/components/preview/kitchen-sink.html. Try adding `bg--` colors to the body class and verify that the captions are still accessible. 
- Try adding `bg--white` and `bg--gray` background colors to https://uids.brand.uiowa.edu/branches/feature_figcaption_fix/components/preview/main-menu.html and verify that the link color does not turn blue. 
- Go to https://uids.brand.uiowa.edu/branches/feature_figcaption_fix/components/preview/kitchen-sink.html and verify that link color within table caption is gold on all background colors.  Try adding `bg--white` and `bg--gray` to the body class and verify that the table caption is still gold.

### CODE REVIEW

**Comment by GaryRidgway** [comment]
Is this of worry? It is when I add a bg-- class to the body:
0de592bc6dcd8f03bbd3c05bc49eefec

**Comment by bspeare** [comment]
@GaryRidgway at this point, it is not a concern.   I just want to make sure they are accessible for now.  Nested background will change some colors based on the color they inherit from the rules set in `backgrounds.scss`.  We could certainly do more work in the future to verify that nested backgrounds have the same colors as regular backgrounds.

**Comment by GaryRidgway** [comment]
Okay! no worries then, almost done!

**Review by GaryRidgway — APPROVED** [review]
All test steps described seem to be good!

**Comment by bspeare** [comment]
Thanks @GaryRidgway!

**Pull request merged**
