### PR TITLE
Feature: banner aspect ratio and gradient/opacity updates

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uids/issues/461.
Resolves https://github.com/uiowa/uids/issues/464. 
Resolves https://github.com/uiowa/uids/issues/467. 
Resolves https://github.com/uiowa/uids/issues/472. 

# How to test https://github.com/uiowa/uids/issues/461
- Verify that https://localhost:3000/components/preview/banner--default scales up and down until it hits the container breakpoint and then sits at a set height.   Try adding `banner--scale` modifier class to override set height and allow scaling beyond container breakpoint.  Also try adding `banner--full` modifier class to override the set height and allow `100vh` scaling. 
- Go to https://localhost:3000/components/preview/banner--medium_centered_banner and verify that the medium size banner scales up and down until it hits the container breakpoint and then sits at a set height.   Try adding `banner--scale` modifier class to override set height and allow scaling beyond container breakpoint.
- Go to https://localhost:3000/components/preview/banner--small_centered_banner and verify that the small scales up and down until it hits the container breakpoint and then sits at a set height.   Try adding `banner--scale` modifier class to override set height and allow scaling beyond container breakpoint.

# How to test https://github.com/uiowa/uids/issues/464
- Test https://localhost:3000/components/preview/banner--default, https://localhost:3000/components/preview/banner--medium_centered_banner, https://localhost:3000/components/preview/banner--small_centered_banner and verify that the gradient only changes to an opacity below the `sm` breakpoint.  

# How to test https://github.com/uiowa/uids/issues/467
- Add `banner--transparent` modifier class to the `banner` on https://localhost:3000/components/preview/banner--default, https://localhost:3000/components/preview/banner--medium_centered_banner, https://localhost:3000/components/preview/banner--small_centered_banner and verify that the gradient overlay is removed. 

# How to test Play button bug fix https://github.com/uiowa/uids/issues/472
- Go to https://localhost:3000/components/preview/banner--video and resize the browser and verify that play button is not obscured by the banner content.

### CODE REVIEW

**Comment by joewhitsitt** [comment]
pulling down for testing

**Review by joewhitsitt — APPROVED** [review]
Test steps worked. `will-change` is new to me.

**Comment by pyrello** [comment]
@joewhitsitt Wanted to check if you had any concerns about dropping these changes on users, since the effect is quite a bit different in terms of how the banners render at different device sizes.

**Comment by joewhitsitt** [comment]
I didn't test in the context of Drupal so maybe it was not as noticeable (the aspect changes). I don't think it is too much to drop on folks. Most folks build with desktop in mind and just assume we are handling things properly for smaller devices. The others seem to be bug fixes and things we can start to leverage going forward.

**Comment by pyrello** [comment]
Looks like there was a change since I tested this that limits the impact I was concerned about. Thanks for testing!

**Pull request merged**
