### PR TITLE
Details accordions

### PR DESCRIPTION
**Pull request by GaryRidgway**
This PR converts the accordion element from a javascript based component to a `<details>` based component. I worked off of [this comments task list](https://github.com/uiowa/uiowa/issues/4004#issuecomment-2515228954) to do the conversion.

## To test
1. Code review
2. Check to see that you can using `cmd + f` to search inside closed accordions.
3. Test single- and multi-selectable functionality.
4. Confirm that most recently clicked accordion item's heading ID becomes the URL hash fragment.
5. Confirm that loading a particular accordion as open via URL hash fragment works.
6. Ensure that accordions can be navigated using VoiceOver. VO should report the accordion items as `x of 4` and their initial state as expanded or collapsed. When using `ctrl + option + space` to "activate" an accordion item, VO should report the items new state as collapsed or expanded.

### CODE REVIEW

**Comment by pyrello** [comment]
Pulling to test.

**Comment by pyrello** [comment]
This is ready for testing.

**Comment by james917** [comment]
Pulling to test

**Comment by james917** [comment]
PR is approved everything looks good

**Review by james917 — APPROVED** [review]
Approved everything works as expected.

**Pull request merged**
