### PR TITLE
Intro Text Changes

### PR DESCRIPTION
**Pull request by bewoldt**
Proposed changes to Intro Text feature.

- Smaller font size. Feels odd to have the intro text larger than the H2.
- Increased line-height for spacing
- Removes additional margin-bottom and defaults to regular paragraph margin-bottom.

Before
Screen Shot 2021-05-27 at 10 24 10 AM

After
Screen Shot 2021-05-27 at 10 50 28 AM

### CODE REVIEW

**Comment by bspeare** [comment]
@bewoldt This seems like a good change.  Would you be willing to move up to `2.1rem`?

**Comment by bewoldt** [comment]
> @bewoldt This seems like a good change. Would you be willing to move up to `2.1rem`?

@bspeare 2.1rem is fine.

**Comment by bspeare** [comment]
@bewoldt I adjusted the line-height a bit as well and adjusted the font size for the bold option because Zilla has a smaller height than roboto.  Can you review the changes?

**Comment by bspeare** [comment]
Also, there is work happening in https://github.com/uiowa/uids/pull/561 that will increase the `<h2>` size for Zilla so that it has a similar height to the Roboto `<h2>`.

**Comment by bewoldt** [comment]
I still think it's slightly larger than it needs to be but definitely better than it was before.

**Comment by bspeare** [comment]
OK, let's wait until https://github.com/uiowa/uids/pull/561 merges and then adjust as necessary.

**Comment by bewoldt** [comment]
I just discover you have a .lead class name too. Is the Intro Text meant to replace this? Are you keeping .lead? https://pharmacy.uiowa.edu/pharmacy_practice

**Comment by bspeare** [comment]
We intend to replace `.lead` with this set of styles.

**Review by bspeare — APPROVED** [review]
Let's go with this and revisit in a future pull request if we still aren't happy with it.

**Pull request merged**
