### PR TITLE
[Stat] Hover fix

### LINKED ISSUE #947: Stat component transition causes abrupt change in parent component height
# Motivation

The stat component has a feature where you can hover over it to display additional information. The hover triggers a transition on the component that causes it to move upwards by 10 pixels. While the transition itself is a smooth movement, it appears to cause the parent container to increase its height abruptly and that causes content after the stat block to jump in a disconcerting way.

statSizeJump
Screen capture credit: @GaryRidgway 

# Proposed solution
Apply a transition to affect the height of the stat container so that the movement to the new height appears smooth like the movement of the stat itself.

### PR DESCRIPTION
**Pull request by bspeare**
Resolves https://github.com/uiowa/uids/issues/947. 

# How to test

1. Test `stat_hover` in all of the Stat stories. 
2. Confirm new `stat_hover` control works. 

- Chrome transition will be very smooth
- Safari and Firefox will be better than it currently is but not as smooth as Chrome

### CODE REVIEW

**Comment by GaryRidgway** [comment]
Pulling for review

**Comment by GaryRidgway** [comment]
Made a tiny change to give us some flexibility. We should be able to use it in all browsers now!

**Comment by e-marie-w** [comment]
Stat hover works and looks good, I tested in all three browsers mentioned. I see we have a story for Grid but it is not listed in the display property like default and horizontal are. I can try to get that working.

**Comment by e-marie-w** [comment]
Wait default and horizontal can be applied to the grid, nevermind.

**Review by e-marie-w — APPROVED** [review]
Everything looks and works as expected

**Comment by bspeare** [comment]
Thanks @e-marie-w!

**Pull request merged**
